
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name    = "line_bot_sdk_rs"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64      = "0.22"
bytes       = "1"
hmac        = "0.12"
napi-derive = "3.0.0"
serde_json  = "1"
sha2        = "0.10"

  [dependencies.napi]
  features = ["async"]
  version  = "3.0.0"

  [dependencies.reqwest]
  features = ["json", "multipart"]
  version  = "0.12"

  [dependencies.serde]
  features = ["derive"]
  version  = "1"

[build-dependencies]
napi-build = "2"

[profile.release]
lto   = true
strip = "symbols"
