/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class LineClient {
  constructor(args: LineClientArgs)
  verify(): Promise<BotInfo>
  getGroupSummary(groupId: string): Promise<GroupSummary>
  getGroupMembersCount(groupId: string): Promise<number>
  getGroupMemberProfile(groupId: string, userId: string): Promise<GroupMemberProfile>
  getGroupMemberIds(groupId: string, next?: string | undefined | null): Promise<MemberIds>
  leaveGroup(groupId: string): Promise<string>
  getRoomMemberProfile(roomId: string, userId: string): Promise<GroupMemberProfile>
  getRoomMemberIds(roomId: string, next?: string | undefined | null): Promise<MemberIds>
  leaveRoom(roomId: string): Promise<string>
  /** `date` format: YYYYMMDD (e.g. "20240101") */
  getMessageDeliveryOverview(date: string): Promise<MessageDeliveryOverview>
  /** `date` format: YYYYMMDD */
  getFollowersInsight(date: string): Promise<FollowersInsight>
  getDemographic(): Promise<string>
  getWebhookEndpoint(): Promise<string>
  pushMessage(to: string, text: string): Promise<string>
  narrowcastMessage(messagesJson: string): Promise<string>
  messageContentPreview(messageId: string): Promise<Buffer>
  replyMessage(replyToken: string, text: string): Promise<string>
  /**
   * Send any message types. `messages_json` = JSON array string.
   * e.g. '[{"type":"text","text":"Hi"},{"type":"image",...}]'
   */
  pushMessages(to: string, messagesJson: string): Promise<string>
  /** Reply with any message types. `messages_json` = JSON array string. */
  replyMessages(replyToken: string, messagesJson: string): Promise<string>
  /** Multicast to multiple users. `user_ids_json` = JSON string array. */
  multicast(userIdsJson: string, messagesJson: string): Promise<string>
  /** Broadcast to all followers. `messages_json` = JSON array string. */
  broadcast(messagesJson: string): Promise<string>
  getMessageQuota(): Promise<MessageQuota>
  getMessageQuotaConsumption(): Promise<MessageQuotaConsumption>
  getMessageContent(messageId: string): Promise<Buffer>
  getProfile(userId: string): Promise<Profile>
  /** Returns follower user IDs. Pass `next` cursor for pagination (empty string for first page). */
  getFollowerIds(next?: string | undefined | null): Promise<FollowerIds>
  createRichMenu(richMenu: RichMenu): Promise<string>
  getRichMenuDefault(): Promise<RichMenuIdResponse>
  getRichMenu(richMenuId: string): Promise<RichMenuResponse>
  deleteRichMenu(richMenuId: string): Promise<string>
  getRichMenuList(): Promise<RichMenuList>
  /** Upload rich menu image. `content_type` is e.g. "image/jpeg" or "image/png". */
  uploadRichMenuImage(richMenuId: string, imageData: Buffer, contentType: string): Promise<string>
  /** Download rich menu image. Returns raw bytes as Buffer. */
  downloadRichMenuImage(richMenuId: string): Promise<Buffer>
  setDefaultRichMenu(richMenuId: string): Promise<string>
  cancelDefaultRichMenu(): Promise<string>
  getUserRichMenu(userId: string): Promise<RichMenuIdResponse>
  linkRichMenuToUser(userId: string, richMenuId: string): Promise<string>
  unlinkRichMenuFromUser(userId: string): Promise<string>
  /** Bulk link rich menu to multiple users. `user_ids_json` = JSON array string. */
  bulkLinkRichMenu(richMenuId: string, userIdsJson: string): Promise<string>
  /** Bulk unlink rich menu from multiple users. `user_ids_json` = JSON array string. */
  bulkUnlinkRichMenu(userIdsJson: string): Promise<string>
}

export interface AudioMessage {
  messageType: string
  originalContentUrl: string
  duration: number
  quickReply?: QuickReply
}

export interface BeaconContent {
  hwid: string
  beaconType: string
  dm?: string
}

export interface BotInfo {
  userId: string
  basicId: string
  displayName: string
  pictureUrl: string
  chatMode: string
  markAsReadMode: string
}

export interface ContentProvider {
  providerType: string
  originalContentUrl?: string
  previewImageUrl?: string
}

export interface DeliveryContext {
  isRedelivery: boolean
}

export interface EventMessage {
  id: string
  messageType: string
  text?: string
  contentProvider?: ContentProvider
  duration?: number
  fileName?: string
  fileSize?: number
  title?: string
  address?: string
  latitude?: number
  longitude?: number
  packageId?: string
  stickerId?: string
  stickerResourceType?: string
}

export interface EventSource {
  sourceType: string
  userId?: string
  groupId?: string
  roomId?: string
}

export interface FollowerIds {
  userIds: Array<string>
  next?: string
}

export interface FollowersInsight {
  status: string
  followers?: number
  targetedReaches?: number
  blocks?: number
}

export interface GroupMemberProfile {
  displayName: string
  userId: string
  pictureUrl?: string
}

export interface GroupSummary {
  groupId: string
  groupName: string
  pictureUrl?: string
}

export interface ImageMessage {
  messageType: string
  originalContentUrl: string
  previewImageUrl: string
  quickReply?: QuickReply
}

export interface LineClientArgs {
  accessToken: string
}

export interface LinkContent {
  result: string
  nonce: string
}

export interface LocationMessage {
  messageType: string
  title: string
  address: string
  latitude: number
  longitude: number
  quickReply?: QuickReply
}

export interface MemberIds {
  memberIds: Array<string>
  next?: string
}

export interface MessageDeliveryOverview {
  status: string
  broadcast?: number
  targeting?: number
}

export interface MessageQuota {
  quotaType: string
  value?: number
}

export interface MessageQuotaConsumption {
  totalUsage: number
}

/**
 * Parse a webhook body JSON string into typed events.
 * Throws if the JSON is invalid.
 */
export declare function parseWebhookBody(body: string): WebhookBody

export interface PostbackContent {
  data: string
  params?: PostbackParams
}

export interface PostbackParams {
  date?: string
  time?: string
  datetime?: string
}

export interface Profile {
  displayName: string
  userId: string
  pictureUrl?: string
  statusMessage?: string
}

export interface PushMessageRequest {
  to: string
  messages: Array<TextMessage>
}

export interface QuickReply {
  items: Array<QuickReplyItem>
}

export interface QuickReplyAction {
  actionType: string
  label: string
  text?: string
  data?: string
  uri?: string
}

export interface QuickReplyItem {
  itemType: string
  action: QuickReplyAction
  imageUrl?: string
}

export interface ReplyMessageRequest {
  replyToken: string
  messages: Array<TextMessage>
}

export interface RichMenu {
  size: RichMenuSize
  selected: boolean
  name: string
  chatBarText: string
  areas: Array<RichMenuArea>
}

export interface RichMenuAction {
  actionType: string
  label?: string
  text?: string
  uri?: string
  data?: string
}

export interface RichMenuArea {
  bounds: RichMenuBounds
  action: RichMenuAction
}

export interface RichMenuBounds {
  x: number
  y: number
  width: number
  height: number
}

export interface RichMenuIdResponse {
  richMenuId: string
}

export interface RichMenuList {
  richmenus: Array<RichMenuResponse>
}

export interface RichMenuResponse {
  richMenuId: string
  size: RichMenuSize
  selected: boolean
  name: string
  chatBarText: string
  areas: Array<RichMenuArea>
}

export interface RichMenuSize {
  width: number
  height: number
}

export interface Sender {
  name?: string
  iconUrl?: string
}

export interface StickerMessage {
  messageType: string
  packageId: string
  stickerId: string
  quickReply?: QuickReply
}

export interface TextMessage {
  messageType: string
  text: string
  quickReply?: QuickReply
  sender?: Sender
}

export interface VerifySignatureArgs {
  body: string
  signature: string
  channelSecret: string
}

/**
 * Verify the X-Line-Signature header against the raw request body.
 * Returns true if the signature is valid.
 */
export declare function verifyWebhookSignature(args: VerifySignatureArgs): boolean

export interface VideoMessage {
  messageType: string
  originalContentUrl: string
  previewImageUrl: string
  trackingId?: string
  quickReply?: QuickReply
}

export interface WebhookBody {
  destination: string
  events: Array<WebhookEvent>
}

export interface WebhookEvent {
  eventType: string
  timestamp: number
  source: EventSource
  webhookEventId?: string
  deliveryContext?: DeliveryContext
  replyToken?: string
  message?: EventMessage
  postback?: PostbackContent
  beacon?: BeaconContent
  link?: LinkContent
}
